### ISSUE TITLE
Can not registration user information

### ISSUE THREAD

**Issue by NozomiSugiyama** [is09-souzou/portal-web#121]
ミニファイエラーが起きてそう。
本番環境でSign In後にsign upができない。
<img width="631" alt="screen shot 2019-01-22 at 18 14 33" src="https://user-images.githubusercontent.com/19605052/51524618-de3a2100-1e71-11e9-8b15-3088ec3ef6f3.png">

**Comment by NozomiSugiyama** [comment]
一度更新したら治った。
原因不明。

closeするが、再発しないか都度確認する。

**Comment by NozomiSugiyama** [comment]
原因の可能性
<img width="743" alt="screen shot 2019-01-22 at 18 38 01" src="https://user-images.githubusercontent.com/19605052/51526052-e21b7280-1e74-11e9-8c94-63d0569cb9b2.png">

**Comment by Shuhei28** [comment]
- iPhoneXS MAX iOS 12.1.2のSafari

<img width="848" alt="screen shot 2019-01-22 at 18 37 40" src="https://user-images.githubusercontent.com/29674414/51526061-e6479000-1e74-11e9-976e-ca65a94a2e0b.png">

**Comment by NozomiSugiyama** [comment]
なぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞなぞ

**Comment by NozomiSugiyama** [comment]
UIやばいやつ
<img width="320" alt="screen shot 2019-01-22 at 20 45 18" src="https://user-images.githubusercontent.com/19605052/51533598-b99c7400-1e86-11e9-90ee-dffe20dcadf5.png">
