### ISSUE TITLE
Update application collaboration key of Cognito on environment

### ISSUE THREAD

**Issue by hashiserver** [is09-souzou/portal-web#17]
# Update application collaboration key of Cognito on environment
## portal-web OverView
Cognito User pool の更新に伴い、application collaboration keyの更新を行う.

## Changes
- config.js

### Problem
現状Cognitoのユーザー名をemailとしており、今後のfeatureとしてのemailのupdateの実装を進めることができない。

## Change
- User poolの再作成.
  + email Updateのため、ユーザー名を一意のIDとして指定。
  + emailを標準属性とし、IDもしくは、email両方でのログインを可能とする。

## Supplement
- [ ] create custom message triggerの追加
- [ ] custom payload にdisplay nameを追加
- Application collaboration key  の作成
  + [ ] AppSync for Developer
  + [ ] create s3 signed uri lambda
  + [ ] portal-web
- email確認用送信メール本文のカスタマイズ
  + [ ] create custom domail
  + [ ] change send type to tag
- 環境変数の更新
  + [ ] create s3 signed uri lambdaのenv更新

**Comment by NozomiSugiyama** [comment]
経過報告
- [x] create custom message triggerの追加
- [x] custom payload にdisplay nameを追加
- Application collaboration key  の作成
  + [x] AppSync for Developer
  + [x] create s3 signed uri lambda
  + [x] portal-web
- email確認用送信メール本文のカスタマイズ
  + [ ] create custom domain
  + [ ] change send type to tag
- 環境変数の更新
  + [ ] create s3 signed uri lambdaのenv更新

**Comment by NozomiSugiyama** [comment]
経過報告
- [x] create custom message triggerの追加
- [x] custom payload にdisplay nameを追加
- Application collaboration key  の作成
  + [x] AppSync for Developer
  + [x] create s3 signed uri lambda
  + [x] portal-web
- email確認用送信メール本文のカスタマイズ
  + [x] create custom domain
  + [x] change send type to tag
- 環境変数の更新
  + [x] create s3 signed uri lambdaのenv更新


portal-webでのuser nameをフロントエンドで自動作成するように変更が必要。

**Comment by NozomiSugiyama** [comment]
上記に伴い同時に修正
https://github.com/is09-souzou/cognito-create-custom-message/commit/d5e69ef92494c2cd86e5d4470ab92905191d6f30

**Comment by NozomiSugiyama** [comment]
再度修正。
https://github.com/is09-souzou/cognito-create-custom-message/commit/533560de49a22488f80844f79e318326087353fb

**Comment by NozomiSugiyama** [comment]
本番環境での動作確認、終了しました...。
終了しました...。
